---
title: "Stat_4911_PracticeProject"
author: "Tyler Celleghin (Celleghin.2)"
date: "2026-01-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(nycflights13)
library(dplyr)
library(glmnet)
```

```{r}
data("flights")
#flights

data("weather")

data("planes")

data("airports")

#View(flights)
#View(weather)
#View(planes)
#View(airports)
```

```{r}
##join flights and planes datasets
dataset = left_join(flights, planes, by = "tailnum")
#dataset = merge(dataset, weather, by = "time_hour")

#remove observations without matching planes
dataset = dataset %>% filter(!is.na(year.y))

#Remove unnecessary columns
dataset = dataset %>% select(-year.x, -hour, -minute, -speed)

#Rename year.y to provide more context
dataset = dataset %>% rename(year_constructed = year.y)



##join previous dataset with weather
dataset = left_join(dataset, weather, by = c("time_hour", "origin"))

#Check number of non-NA columns in combined dataset
dataset = dataset %>% filter(!is.na(wind_gust))

#remove duplicate columns
dataset = dataset %>% select(-year, -month.y, -day.y, -wind_gust)

#rename columns to more intuitive names
dataset = dataset %>% rename(month = month.x,
                             day = day.x)


#univariate analysis of flights data
hist(na.omit(flights$dep_delay),
     breaks = 50,
     main = "Histogram of Departure Delay",
     xlab = "Delay (minutes)")

summary(flights$dep_delay)

hist(flights$dep_time,
     main = "Histogram of Departure Time",
     xlab = "Military Time",
     col = "lightgray",
     border = "white")

hist(flights$sched_dep_time,
     main = "Histogram of Scheduled Departure Time",
     xlab = "Military Time",
     col = "lightgray",
     border = "white")

hist(flights$arr_time,
     main = "Histogram of Arrival Time",
     xlab = "Military Time",
     col = "lightgray",
     border = "white")

hist(flights$sched_arr_time,
     main = "Histogram of Scheduled Arrival Time",
     xlab = "Military Time",
     col = "lightgray",
     border = "white")

hist(flights$arr_delay,
     main = "Histogram of Arrival Delay",
     xlab = "Delay (minutes)",
     col = "lightgray",
     border = "white")

summary(flights$arr_delay)


barplot(table(flights$carrier),
        main = "Flight Counts by Carrier",
        ylab = "Count",
        las = 2)

barplot(table(flights$tailnum),
        main = "Category Counts",
        ylab = "Count")

tail_counts <- sort(table(flights$tailnum), decreasing = TRUE)[1:10]

barplot(tail_counts,
        main = "Top 10 Most Frequent Aircraft (Tail Numbers)",
        ylab = "Number of Flights",
        las = 2)

barplot(table(flights$origin),
        main = "Category Counts",
        ylab = "Count")

barplot(table(flights$dest),
        main = "Category Counts",
        ylab = "Count")

hist(flights$air_time,
     main = "Histogram of Air Time",
     xlab = "Minutes",
     col = "lightgray",
     border = "white")

summary(flights$air_time)

hist(flights$distance,
     main = "Histogram of Distance",
     xlab = "Miles",
     col = "lightgray",
     border = "white")

summary(flights$distance)

#join flights with planes and look at categoricals affect on departure delay
flight_planes <- flights %>%
  left_join(planes, by = "tailnum")

plot(flight_planes$year.y, flight_planes$dep_delay,
     xlab = "Plane Year Constructed",
     ylab = "Departure Delay (minutes)")

cor(flight_planes$year.y, flight_planes$dep_delay, use = "complete.obs")

model1 <- lm(dep_delay ~ year.y, data = flight_planes)
summary(model1)


boxplot(dep_delay ~ type, data = flight_planes)

model_type <- lm(dep_delay ~ type, data = flight_planes)
summary(model_type)

flight_planes %>%
  count(manufacturer) %>%
  filter(n > 1000)

boxplot(dep_delay ~ manufacturer, data = flight_planes)

model_manu <- lm(dep_delay ~ manufacturer, data = flight_planes)
summary(model_manu)

```



